services:
  zookeeper:
    container_name: exercise-zookeeper
    image: confluentinc/cp-zookeeper:5.3.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "echo ruok | nc localhost 2181 || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 3

  kafka:
    container_name: exercise-kafka
    image: confluentinc/cp-kafka:5.3.1
    depends_on:
      zookeeper:
        condition: service_healthy
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "9092"]
      interval: 10s
      timeout: 10s
      retries: 3

  oracle:
    container_name: exercise-bd
    image: container-registry.oracle.com/database/express:21.3.0-xe
    environment:
      - DBCA_TOTAL_MEMORY=1024
      - WEB_CONSOLE=true
      - ORACLE_PWD=oracle
    ports:
      - 1580:8080
      - 1521:1521
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "sh", "-c", "echo 'exit' | sqlplus system/oracle@//localhost:1521/xe"]
      interval: 10s
      timeout: 10s
      retries: 1
      start_period: 90s

  client-service:
    container_name: client-service
    build:
      context: ./client_service
    ports:
      - "8080:8080"
    depends_on:
      oracle:
        condition: service_healthy
      kafka:
        condition: service_healthy
    networks:
      - app-network

  transaction-service:
    container_name: transaction-service
    build:
      context: ./transaction_service
    ports:
      - "8081:8081"
    depends_on:
      oracle:
        condition: service_healthy
      kafka:
        condition: service_healthy
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
